### ISSUE TITLE
Typo in the lesson

### ISSUE THREAD

**Issue by nikimar1** [fmof/loglin#113]
In lesson 15 the statement "When triangle & solid and square & solid are the same color (e.g., both have red hints, meaning they need to be increased), then what color is solid? " includes a feature not present in the model since the possible shapes are circle pentagon and triangle.

**Comment by jeisner** [comment]
Corrected in b848131daf2f6290ea1a2247eede633296fa7e90, thanks.

**Comment by jeisner** [comment]
Edited the correction; should be correct now.
https://www.cs.jhu.edu/~jason/tutorials/loglin/#15
